version: '3'

services:
  web: 
    build: .

    image: node:16
    depends_on: 
      - db

    ports:
      - "3333:3333"

    environment:
      DATABASE_URL: "postgres://postgres:123@db:5432/onebitjobs_development"
      NODE_ENV: "development"

    networks:
      - api-sequelize

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "49555:5432"

    networks:
      - api-sequelize

networks:
  api-sequelize:
    driver: bridge